devnamespace: dev
personalApplicationName: personal-app

personalimage: 
  name: 416591745024.dkr.ecr.eu-west-2.amazonaws.com/personal-demo/personal-app
  tag: "latest"



personalservice: personal-app-service
serviceingress:  personal-ingress-service
personalappbaseURL : personal.globalfrontierlink.co.uk