apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.personalservice }}
  namespace: {{ .Values.devnamespace }}
spec:
  selector:
    app: {{ .Values.personalApplicationName }}
  ports:
  - port: 80
    targetPort: 80
  
  type: ClusterIP
