apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.serviceingress }}
  namespace: {{ .Values.devnamespace }}
  labels:
    name: {{ .Values.serviceingress }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.personalappbaseURL }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Values.personalservice }}
            port: 
              number: 80



